branch-defaults:
  main:
    environment: lab2-arqui-soft
deploy:
  artifact: target/lab2-arqui-soft-0.0.1-SNAPSHOT.jar
global:
  application_name: lab2-arqui-soft
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 21 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
